/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame1;

import javax.swing.JOptionPane;
import static sun.security.krb5.Confounder.intValue;

/**
 *
 * @author ASUS
 */
public class Frame1 extends javax.swing.JFrame {
    String temp="";
    Double ti, bt, sil;

    /**
     * Creates new form Frame1
     */
    public Frame1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Nama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Tinggi = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Berat = new javax.swing.JTextField();
        rdb1 = new javax.swing.JRadioButton();
        rdb2 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Ideal = new javax.swing.JTextField();
        Saran = new javax.swing.JTextField();
        Hasil = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("CEK IDEAL TUBUH");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 10, 90, 40);

        jLabel2.setText("Nama");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 60, 80, 30);
        getContentPane().add(Nama);
        Nama.setBounds(130, 50, 180, 30);

        jLabel3.setText("Tinggi");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 100, 70, 20);
        getContentPane().add(Tinggi);
        Tinggi.setBounds(130, 90, 50, 30);

        jLabel4.setText("Berat Badan");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 140, 70, 20);
        getContentPane().add(Berat);
        Berat.setBounds(130, 130, 50, 30);

        buttonGroup1.add(rdb1);
        rdb1.setText("Laki - Laki");
        rdb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb1ActionPerformed(evt);
            }
        });
        getContentPane().add(rdb1);
        rdb1.setBounds(130, 170, 80, 30);

        buttonGroup1.add(rdb2);
        rdb2.setText("Perempuan");
        getContentPane().add(rdb2);
        rdb2.setBounds(220, 170, 100, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Jenis Kelamin");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 170, 90, 30);

        jButton1.setText("Keluar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(240, 230, 70, 30);

        jButton2.setText("Coba Lagi");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(120, 230, 100, 30);

        jButton3.setText("Hitung");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(20, 230, 70, 30);

        jLabel5.setText("Berat Badan Ideal Anda Adalah");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 280, 200, 30);

        jLabel7.setText("Kg");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(190, 140, 34, 14);

        Ideal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdealActionPerformed(evt);
            }
        });
        getContentPane().add(Ideal);
        Ideal.setBounds(220, 280, 60, 30);
        getContentPane().add(Saran);
        Saran.setBounds(20, 380, 310, 30);
        getContentPane().add(Hasil);
        Hasil.setBounds(20, 350, 310, 30);

        jLabel8.setText("Hasil Diagram Kesehatan");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(110, 320, 120, 20);

        jLabel9.setText("Cm");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(190, 100, 34, 14);

        jLabel10.setText("Kg");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(290, 290, 34, 14);

        setBounds(0, 0, 677, 542);
    }// </editor-fold>//GEN-END:initComponents

    private void rdb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdb1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (Nama.getText().equals("")||Tinggi.getText().equals("")||Berat.getText().equals("")){
            JOptionPane.showMessageDialog( null, "Data Harus Diisikan Semua");
        }else if(rdb1.isSelected()||rdb2.isSelected()){
            try{
                Proses();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Inputan Belum Diisi");
            }
            
        }else{
            JOptionPane.showMessageDialog(null,"Radio Button Harus diisi");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void IdealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdealActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdealActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Nama.setText("");
        Tinggi.setText("");
        Berat.setText("");
        buttonGroup1.clearSelection();  
        Ideal.setText("");
        Hasil.setText("");
        Saran.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame1().setVisible(true);
            }
        });
    }
    private void Proses(){
        ti = Double.parseDouble(Tinggi.getText());
        bt = Double.parseDouble(Tinggi.getText());
        
        if (rdb1.isSelected()){
            sil = (ti - 100) * 1;
        }else if(rdb2.isSelected()){
            sil = (ti - 104) * 1;
        }
        
        temp = Double.toString(sil.intValue());
        
        if (sil > bt) {
            Ideal.setText(temp);
            Hasil.setText("Maaf " + Nama.getText()+", Sepertinya anda Overweight");
            Saran.setText("Banyaklah Berolahraga dan Hindari Makanan Berkolesterol Tinggi");
        }else if (sil < bt){
            Ideal.setText(temp);
            Hasil.setText("Maaf " + Nama.getText()+", Sepertinya anda Underweight");
            Saran.setText("Banyaklah Mengkonsumsi makanan yang berkarbohidrat");
        }else{
            Ideal.setText(temp);
            Hasil.setText("Hallo " + Nama.getText()+", Berat Badan anda sudah Ideal");
            Saran.setText("Lanjutkan pola makan teratur dan gaya hidup sehat :D");
        }
                
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Berat;
    private javax.swing.JTextField Hasil;
    private javax.swing.JTextField Ideal;
    private javax.swing.JTextField Nama;
    private javax.swing.JTextField Saran;
    private javax.swing.JTextField Tinggi;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton rdb1;
    private javax.swing.JRadioButton rdb2;
    // End of variables declaration//GEN-END:variables
}
